user_name = input('What is your name?\n')
print('Hello,', user_name, end = '\n\n')
user_age = input('What old are you?\n')
print ('Your age is', user_age, end = '\n\n')
user_local = input('Where ado you live?\n')
print('You live in', user_local)
